### PR TITLE
test steps and expected result for registration and profile page added

### PR DESCRIPTION
**Pull request by trish1102**

### CODE REVIEW

**Comment by trish1102** [comment]
please check everyone

**Comment by William-436** [comment]
Registration - Use fewer words in Expected Results. 'should be able to' is implied and can be removed. Just write what is visible without implied words.

**Comment by William-436** [comment]
Registration - Please replace 'page' with 'pop-up window' in Step 2's Expected Result for all Test Cases.  Whatever opens (pops-up) over an existing page - and subsequently closes after performing an action - is known as a pop-up window. A page covers the entire window but a pop-up window covers only a portion of a page.

**Comment by William-436** [comment]
Registration - Please capitalize page names in all columns.

**Comment by William-436** [comment]
Registration - Please clearly state the specific invalid value to be used in the Test Steps for TC_Rg01_01, TC_Rg02_01, TC_Rg03_01, & TC_Rg03_02

**Comment by William-436** [comment]
Registration - Please change Step 4 of TC_Rg02_02's Expected Result to reference LastName.

**Comment by William-436** [comment]
Registration - Please remove 'except password' from TC_Rg04_02's Test Step because password's value is valid. Provide more detail in Step 5's Expected Result. Maybe use TC_Rg06_01's Step 4 Expected Result with more detail. This would allow for the removal of TC_Rg06_01 entirely.

**Comment by William-436** [comment]
Registration - Were you expecting the error message to display in TC_Rg04_03, 04, & 05 without clicking the "Join" button? If yes, then disregard this question/comment.

**Comment by William-436** [comment]
Registration - Can you add more detail to TC_Rg06_02's Step 3's Expected Result that the correct user is logged on?

**Comment by William-436** [comment]
Registration - Please replace 'page' with 'pop-up window' in Step 3's Expected Result in TC_Rg07_01.

**Comment by William-436** [comment]
Profile - Please add Test Cases for "Description" Test Conditions.

**Comment by William-436** [comment]
Profile - Please add type of object - after clicking on the object - in Step 5 of all test cases. ie. button, hyperlink, label, '... icon', etc.

**Comment by William-436** [comment]
Profile - Please combine Steps 5 & 6 into a single step in all TC_Pr10_nn test cases and replace "Trupti" with generic text. ie. user's First Name or '...'

**Comment by William-436** [comment]
Profile - Ensure all non-Cancel edit test cases can save the edited value and then verify the saved value.

**Comment by William-436** [comment]
Profile - Confirm the saved password in TC_Pr10_08 & 12 by signing in with the new password.

**Comment by trish1102** [comment]
> Registration - Were you expecting the error message to display in TC_Rg04_03, 04, & 05 without clicking the "Join" button? If yes, then disregard this question/comment.

yes. for password it's show a error message without clicking on join

**Pull request closed without merging**
