### PR TITLE
sign in page test cases

### PR DESCRIPTION
**Pull request by Mohanaguntakatta**
Hi team, Please review the sign in page test cases.

### CODE REVIEW

**Comment by William-436** [comment]
Please create a new sheet in the Excel file containing the 'Sign In Test Conditions'. Simply copy columns A, B, C, & D of the existing sheet into the new sheet. Then rename the existing sheet to 'Sign In Test Cases' and delete columns A and B so that the test cases will have the Test Case ID begin in column A.  This will keep with our standard to have 1 sheet for test conditions and a separate sheet for test cases.

**Comment by William-436** [comment]
Please use a separate row for each step in every test case so that the expected result appears on the same line as the step.

**Comment by William-436** [comment]
Can you replace 'User should be able to...' with a visible difference to the screen to help validate the step was completed -- wherever it seems appropriate in the Expected Results. For example, 'User should be able to click sign in button' is a bit generic and is missing evidence or proof that the screen has changed. Try to briefly describe the difference that happened on the screen after clicking the Sign In link. Hint: look how other team members wrote their Expected Result for the same action.

**Comment by William-436** [comment]
TC_SIn 01_01 - 2nd Expected Result should be moved to correspond with Step 4

**Comment by William-436** [comment]
TC_SIn 02_01 - Please update several of the Expected Results. For example, there is no Password button.

**Comment by William-436** [comment]
TC_SIn 03_01 - Please ensure everything in quotes is spelled and capitalized exactly as it appears on the screen. When we automate a test case we usually copy & paste whatever is in a test case's quotes to verify the automation script is on the correct page, clicks the correct button, or verifies an error message. We don't want the automation script to fail because our test case had a misspelled word for a heading or label or error message. This gets easier the more we practice.
ALSO, please include a short description of a separate pop-up window that appears and remains on the screen when the error message appears.

**Comment by William-436** [comment]
TC_SIn 03_02 - Please add short description of a separate pop-up window that appears and remains on the screen when the error message appears.

**Comment by William-436** [comment]
TC_SIn 03_03 - Test Step 5 is incorrect -- there should be no error message

**Comment by William-436** [comment]
TC_SIn 03_04 - Step 3 and Step 3's Expected Result are not matching each other.

**Comment by William-436** [comment]
TC_Rg 04_01 - How did you validate the 'Remember me?' tick box actually worked?

**Comment by William-436** [comment]
TC_Rg 05_03 - Step 3's input data does not match the Test Case description

**Comment by Mohanaguntakatta** [comment]
> TC_SIn 03_01 - Please ensure everything in quotes is spelled and capitalized exactly as it appears on the screen. When we automate a test case we usually copy & paste whatever is in a test case's quotes to verify the automation script is on the correct page, clicks the correct button, or verifies an error message. We don't want the automation script to fail because our test case had a misspelled word for a heading or label or error message. This gets easier the more we practice. ALSO, please include a short description of a separate pop-up window that appears and remains on the screen when the error message appears.

Hi William, thanks for the review. I will let you know once i am done. Thank you.

**Comment by Mohanaguntakatta** [comment]
> TC_Rg 04_01 - How did you validate the 'Remember me?' tick box actually worked?

Yes, it worked for me.

**Comment by Mohanaguntakatta** [comment]
> TC_SIn 02_01 - Please update several of the Expected Results. For example, there is no Password button.



> 



> TC_SIn 01_01 - 2nd Expected Result should be moved to correspond with Step 4

For the 2nd test step - what would you suggest as the expected result? As on the step 4, I'm validating the exact error message.
23.5.7 - Email address edit box is empty/blank

**Comment by Mohanaguntakatta** [comment]
Added updated sign in test cases

**Pull request merged**
