### PR TITLE
Test steps and expected results for languages skills

### PR DESCRIPTION
**Pull request by HarshithaS98**
Hi Team.. Please check..

### CODE REVIEW

**Comment by William-436** [comment]
Please rename the sheet name to reflect Language test cases appear before the Skill test cases.

**Comment by William-436** [comment]
Are we following a different naming convention for the IDs for both Test Conditions and Test Cases? I thought we were going to follow the same conventions as were shown in the original spreadsheet.

**Comment by William-436** [comment]
Please add a step in Tc-01 and Tc_18 to Click the Login button after entering the username and password.

**Comment by William-436** [comment]
Please capitalize the 1st letter in all Expected Results and the 1st letter after every step # in the Test Steps.

**Comment by William-436** [comment]
Please ensure exact spelling and capitalization is followed when referencing an object's button, tab, heading, comment, hint, drop-down value, etc. label.

**Comment by William-436** [comment]
Please add a step in every test case, if not already in the test case, to focus on and verify 1 or more values that was 'Saved' do match the value you expect. I only mention this because 'user should be able to save the data' is rather vague and if the test case is automated by someone else, then this would allow the automation writer to interpret the expected result to possibly verify something you did not intend for them to look at.

**Comment by William-436** [comment]
TC_03 - Please include 'p' in 'Step 4' and follow same wording in Step 4's Expected Result as was used in previous Test Cases. Data is not entered into a 'button', it is entered into a textbox before then next step clicks the Add button.

**Comment by William-436** [comment]
Beginning with Tc_06 and subsequent Test Cases - Please use consistent object type when referencing the object's type in both the Test Step and the Expected Result. See Step 2.

**Comment by William-436** [comment]
Tc_07 - Please be more specific in Step 5's Expected Result. Does an error message appear? Does the program ignore the clicking of the Add button and leave the entered values on the screen. Does the program refresh/clear the data that was entered and close the data-entry fields?

**Comment by William-436** [comment]
Tc_09 - Step 4's Expected Result should be in Step 5's Expected Result. The duplicate language is rejected only after the Add button is clicked.

**Comment by William-436** [comment]
Tc_10 - Step 4 and 5's Expected Results contradict each other. Please recall comment for Tc_09's Step 4's Expected Result.

**Comment by William-436** [comment]
Tc_15 - Test Condition should be rewritten to be clearer. Include 'Precondition' if record(s) must exist prior to performing the test and the values of the 'Precondition' record(s). Is this test trying to create a duplicate record?

**Comment by William-436** [comment]
Tc-17 - Please add a Precondition to create a record that will be deleted by the test case.

**Comment by William-436** [comment]
Tc_18 - Step 6's Expected Result is incorrect. 'language' level is not the correct label.

**Comment by William-436** [comment]
Tc_20 - Step 3's Expected Result is incorrect. 'language' level is not the correct label.

**Comment by William-436** [comment]
Tc_21 - Step 3's Expected Result is incorrect. 'language' level is not the correct label.

**Comment by William-436** [comment]
Tc_22 - Step 3's Expected Result is incorrect. 'language' level is not the correct label.
Please use exact casing of each word used in Step 5's Expected Result's error message.

**Comment by William-436** [comment]
Tc_23 - Step 3's Expected Result is incorrect. 'language' level is not the correct label.
Step 4's Expected Result does not address the test condition directly. It indirectly, implies a negative result to the test condition/scenario. Please write a direct statement and update the Test Condition to describe how the test case will attempt to accomplish the stated scenario. ie. by using the skill level on a single Skill

**Comment by William-436** [comment]
Tc_24 - Step 3's Expected Result is incorrect. 'language' level is not the correct label.
The 1st word of the error message in Step 5's Expected Result is incorrect and both uses of the word 'Skill' are lower-case in the error message.

**Comment by William-436** [comment]
Tc_25 - Step 3's Expected Result is incorrect. 'language' level is not the correct label.
First word of error message in Step 5's Expected Result is incorrect.
Please add Precondition to create a skill record.

**Comment by William-436** [comment]
Tc_26 - Step 3's Expected Result is incorrect. 'Add New' is a button, not a tab. 'language' level is not the correct label. 
Please rewrite Step 4's Test Step to focus the edit on the Skill name edit box and to leave the Skill Level unchanged.
Please remove reference to 'Add New' anything because the focus is on the edit fields, not on adding anything.
Please add Precondition to create a skill.

**Comment by William-436** [comment]
Tc_27 - Step 3's Expected Result is incorrect. 'language' level is not the correct label.
Replace "'Add New' tab" with "Skill edit box" in Step 4's Test Step and Expected Result.

**Comment by William-436** [comment]
Tc_28 - Step 3's Expected Result is incorrect. 'language' level is not the correct label.
Replace "'Add New' tab" with "Skill name" in Step 4's Test Step and Expected Result.

**Comment by William-436** [comment]
Tc_29 - Please clarify Test Condition. I don't understand the scenario. How many skills exist before the test is executed? Is there only 1 edit button available to click?

**Comment by William-436** [comment]
Tc-_30 - Step 3's Expected Result: Please replace "'Add New' tab" with "Skill name"
Step 3's Expected Result is incorrect. 'language' level is not the correct label.
Step 4's Test Step and Expected Result: Replace "'Add New' tab" with "Skill name".
Step 5's Expected Result: can you add "Edited skill and skill level are unchanged".
Please add Precondition to create a skill record.

**Comment by William-436** [comment]
Tc_31 - Please add Precondition to create a skill record.

**Comment by HarshithaS98** [comment]
> Tc_09 - Step 4's Expected Result should be in Step 5's Expected Result. The duplicate language is rejected only after the Add button is clicked.

hii william.. 
1.5.23 - Tc_09 => TC_LP 01_09 - Ok

**Comment by HarshithaS98** [comment]
> Please rename the sheet name to reflect Language test cases appear before the Skill test cases.

Hii .. Yes I renamed it now.

**Comment by HarshithaS98** [comment]
> Tc_27 - Step 3's Expected Result is incorrect. 'language' level is not the correct label. Replace "'Add New' tab" with "Skill edit box" in Step 4's Test Step and Expected Result.

Now modified as per your comments

1.5.23 - Where did Tc_27 go? I am unable to find it in your updated/uploaded Excel file in Github.
- Pardon my previous comment but I located Tc_27... it is now TC_SP 01_10. Please remember for FUTURE test cases to remove [from Step 4's Test Step and Expected Result columns] references to labels that appear when 'adding' a skill because this test case is an 'Edit' test case so 'add' does not appear in the edited skill's text box, nor does 'Choose Skill Level' appear in the skill level box. Simply state to leave the existing skill unchanged and to change the existing skill level.
- I will mark this comment as closed and only ask that you view my comment

**Pull request closed without merging**
